job('Secon_Maven_Project_Via_DSL'){
    description("Second Maven Job Generated by DSL on ${new Date()}, This is small Project tha is Hosted in Github")
    scm{
        git("https://github.com/lokeshdeepu12/Jenkins.git", master)
    }
    triggers{
        scm('H * * * *')
    }
    steps{
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers{
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
